version: "3.3"
services:
  db:
    image: postgres
    env_file: 
      - fhi/fhi/.env
    environment:
      POSTGRES_USER: fhi
      POSTGRES_DB: map
    volumes:
      - pgdata:/var/lib/posgresql/data
    restart: always
  web:
    build: .
    command: python fhi/manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/usr/src/app
    ports:
        - "1234:8000"
    depends_on:
      - db
    restart: always
volumes:
  pgdata:
