# Generated by Django 3.1 on 2020-12-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20201230_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planttype',
            old_name='short_descroption',
            new_name='short_description',
        ),
    ]
