# Generated by Django 3.1 on 2021-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20201230_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='planttype',
            name='marker_color',
            field=models.CharField(blank=True, choices=[('violet', 'VIOLET'), ('yellow', 'YELLOW'), ('red', 'RED'), ('blue', 'BLUE'), ('gold', 'GOLD'), ('green', 'GREEN'), ('grey', 'GREY'), ('black', 'BLACK'), ('orange', 'ORANGE')], max_length=10, null=True),
        ),
    ]
