# Generated by Django 3.1 on 2021-01-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20210116_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.planttype'),
        ),
    ]
