# Generated by Django 3.1 on 2021-01-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20210116_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
